### ISSUE TITLE
json-diff-ts/dist/index.d.ts have  seven TS1005: ',' expected  errors.

### ISSUE THREAD

**Issue by linconliu** [ltwlf/json-diff-ts#155]
<img width="822" alt="image" src="https://github.com/ltwlf/json-diff-ts/assets/131529240/daa7d741-8eb3-476e-b5d0-021cfc4c3cbd">

version 4.0.1
`
export { type Changeset, CompareOperation, type EmbeddedObjKeysMapType, type EmbeddedObjKeysType, type IAtomicChange, type IChange, type IComparisonEnrichedNode, Operation, type Options, applyChangelist, applyChangeset, atomizeChangeset, compare, createContainer, createValue, diff, enrich, getTypeOfObj, revertChangeset, unatomizeChangeset };
`

when I remove all the 'type' in above export, then compile, it success.

**Comment by ltwlf** [comment]
Hi, this issue might because different versions of typescript. What is your stack and Typescript versions?

**Comment by OmniAndy** [comment]
I have this issue as well.  I'm using typescript@3.5.3.  I can't upgrade higher than that.
