### ISSUE TITLE
Examples do not compile

### ISSUE THREAD

**Issue by hffmnn** [ltwlf/json-diff-ts#180]
Copy & pasting the example given here: https://github.com/ltwlf/json-diff-ts?tab=readme-ov-file#examples-using-star-wars-data gives the following TS Error: `Object literal may only specify known properties, and 'characters' does not exist in type 'Options'.ts(2353)`

## Technicals

- `"typescript": "5.5.3"`
- `"json-diff-ts": "4.0.1"`

**Comment by austinthedeveloper** [comment]
I ran into this too and it took a second to spot the problem. The main example is missing the `embeddedObjKeys`

```
{ embeddedObjKeys: { 'characters': 'id' }}
```
