### ISSUE TITLE
[HELP] I can not make embeddedObjKeys works correctly

### ISSUE THREAD

**Issue by Tusquito** [ltwlf/json-diff-ts#183]
Hi,

I'm currently trying to compare 2 swagger files with a standard json format using this lib.
Here is the json format I'm trying to compare:

```json
{
  "paths": {
    "/foo": {
      "get": {
        "tags": ["Foo"],
        "summary": "Foo",
        "operationId": "Foo",
        "parameters": [
          {
            "name": "Foo1",
            "in": "header",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Foo2",
            "in": "header",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ]
      }
    }
  }
}
```

As you can see in this example, **parameters** is an array of objects, so as a result of the comparison, I've got the object's index in the IChange key, as shown in the following example:

```json
{
    "type": "UPDATE",
    "key": "/foo",
    "changes": [
        {
            "type": "UPDATE",
            "key": "get",
            "changes": [
                {
                    "type": "UPDATE",
                    "key": "parameters",
                    "embeddedKey": "$index",
                    "changes": [
                        {
                            "type": "UPDATE",
                            "key": "0",
                            "changes": [
                                {
                                    "type": "UPDATE",
                                    "key": "schema",
                                    "changes": [
                                        {
                                            "type": "ADD",
                                            "key": "$ref",
                                            "value": "#/foo"
                                        },
                                        {
                                            "type": "REMOVE",
                                            "key": "type",
                                            "value": "string"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
```
Finally, I want to replace the `"embeddedKey": "$index"` by the `name` field of the `parameters` object. To this end, I've added the following options to the `diff()` function, but It does not change the result at all:

`diff(oldSwagger, newSwagger, { embeddedObjKeys: { parameters: 'name' } })`

Can you please explain, what am I doing wrong, and how am I supposed to achieve such things with this library ?

Anyway, thanks for your awesome job.

Regards,

Tusquito.

**Comment by ltwlf** [comment]
Hello Tusquito,

This would only work if the path to parameter would be root/parameters.name. But the parameters is object is deeper in the hierarchy of the swagger.
diff(oldSwagger, newSwagger, { embeddedObjKeys: { parameters: 'name' } })

You can either specify the full path like this:
const diffs = diff(oldData, newData, { embeddedObjKeys: { '.paths./foo.get.parameters': 'name' } });
Or you can sepecify a regex

const embeddedObjKeys: EmbeddedObjKeysMapType = new Map();

embeddedObjKeys.set(/parameters/, 'name');

const diffs = diff(oldObj, newObj, { embeddedObjKeys });

Best,
Christian

**Comment by Tusquito** [comment]
Hello,

Thanks for your quick answer.

This is exactly what I was looking for.

I'm closing this issue.

Thanks again,

Tusquito
