### ISSUE TITLE
Publish recent fix for "Cannot convert undefined or null to object" (when old value is array/object and new undefined)

### ISSUE THREAD

**Issue by kamilzki** [ltwlf/json-diff-ts#185]
Hello! 

I am encountering the "Cannot convert undefined or null to object" error. I see the fix has been implemented in that PR: https://github.com/ltwlf/json-diff-ts/pull/168

Unfortunately, the latest version (v4.0.1) does not seem to include it. The same with v4.0.2-preview. Would it be possible to publish a version that includes this fix?

**Comment by ltwlf** [comment]
Hi, I've published it https://www.npmjs.com/package/json-diff-ts/v/4.0.3-preview 
Looking forward to your feedback.
Best,
Christian

**Comment by ltwlf** [comment]
#186
