### ISSUE TITLE
Safari: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by qwertykeith** [ltwlf/json-diff-ts#2]
Hi! On Safari (most recent mac and iPad), when you use this library there is an error

"Invalid regular expression: invalid group specifier name"

**Comment by ltwlf** [comment]
Thanks for your feedback. I never tested it on a browser. It is primarily intended as a node backend library.

**Comment by leblancmeneses** [comment]
Issue starts here and is related to "Safari doesn't support lookbehind yet". 

https://caniuse.com/js-regexp-lookbehind

https://github.com/ltwlf/json-diff-ts/blob/94418c62875b3d269f6638f99140ee2e9c5985b5/src/jsonDiff.ts#L371

https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

**Comment by leblancmeneses** [comment]
https://github.com/ltwlf/json-diff-ts/pull/19 was pulled and fixed the safari issue.
