### ISSUE TITLE
diff signature for embeddedObjKeys should also allow functions

### ISSUE THREAD

**Issue by abraxxa** [ltwlf/json-diff-ts#27]
This works but is currently blocked by the type definition.
It allows to generate an identifier for objects that have a multi-property natural unique key.

I didn't send a pull-request as it's a one-line change in jsonDiff.d.ts:

`export declare const diff: (oldObj: any, newObj: any, embeddedObjKeys?: Dictionary<string | Function>) => IChange[];`

**Comment by abraxxa** [comment]
Just found out that IChange also has to be changed to:

`embeddedKey?: string | Function;`

**Comment by ltwlf** [comment]
Thanks @abraxxa! Would be great when you send it as a PR :)
