### ISSUE TITLE
JSONPath not valid

### ISSUE THREAD

**Issue by Hoschi1982** [ltwlf/json-diff-ts#85]
Hy there,

the JSONPath is not generated correctly. The following JSONPath is shown in the example on the Github page "https://github.com/ltwl/json-diff-ts#readme": 

"$.children[?( @.name='kid1')].age" 

This JSONPath does not return a correct result. 
It must be "$.children[?( @.name=='kid1')].age" isn't it? Double '='

Is it possible to fix it soon?

Thanks

**Comment by ltwlf** [comment]
Fixed in  #108
